import type { Metadata } from "next";
import { Inter, Exo_2 } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";

// Primary font for body text
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

// Display font for headings
const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://airipening.ru";

export const metadata: Metadata = {
  // Basic Meta Tags
  title: {
    default: "AI.Ripening - ИИ-технолог для созревания сыра",
    template: "%s | AI.Ripening",
  },
  description: "Снижаем брак с 30% до 5%. Первая в России ИИ-система управления созреванием сыра. Точность прогноза 95%, окупаемость 3-6 месяцев.",
  keywords: [
    "ИИ", 
    "сыр", 
    "созревание", 
    "технология", 
    "автоматизация", 
    "сыроварня",
    "искусственный интеллект",
    "контроль качества",
    "молочная продукция",
    "пищевое производство",
    "снижение брака",
    "AI.Ripening"
  ],
  authors: [{ name: "AI.Ripening", url: siteUrl }],
  creator: "AI.Ripening",
  publisher: "AI.Ripening",
  
  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Icons are auto-generated by app/icon.tsx and app/apple-icon.tsx
  
  // Open Graph - for Facebook, LinkedIn, etc.
  openGraph: {
    type: "website",
    locale: "ru_RU",
    url: siteUrl,
    siteName: "AI.Ripening",
    title: "AI.Ripening - ИИ-технолог для созревания сыра",
    description: "Снижаем брак с 30% до 5%. Первая в России ИИ-система управления созреванием сыра. Точность прогноза 95%, окупаемость 3-6 месяцев.",
    // Images are auto-generated by app/opengraph-image.tsx
  },
  
  // Twitter Card - image is auto-generated by app/twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: "AI.Ripening - ИИ-технолог для созревания сыра",
    description: "Снижаем брак с 30% до 5%. Первая в России ИИ-система управления созреванием сыра.",
    creator: "@airipening",
    site: "@airipening",
  },
  
  // Verification (add your actual IDs)
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION,
    yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION,
  },
  
  // Alternate languages (if multilingual)
  alternates: {
    canonical: siteUrl,
    languages: {
      "ru-RU": siteUrl,
    },
  },
  
  // Category
  category: "technology",
  
  // Other
  metadataBase: new URL(siteUrl),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${exo2.variable} font-sans antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
